#联通
spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.4.5:3306/tvq?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: hbwxcm
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.4.5:3306/apa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: hbwxcm
  cache:
    type: redis
  redis:
    database: 0
    host: 192.168.4.5
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  data:
    redis:
      repositories:
        enabled: false
config:
  prefix: http://172.48.3.3:8128/vtvi/
