spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tvq?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/apa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
  jpa:
    show-sql: true
  cache:
    type: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  data:
    redis:
      repositories:
        enabled: false
config:
  prefix: http://localhost:8028/vtvi/
